import type { NextPage } from "next";
import Head from "next/head";
import { GetServerSideProps } from "next";
import Dashboard from "./Dashboard";

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch("http://localhost:8080/api/test/user");
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
};

const Home: NextPage = ({ data }: any) => {
  console.log(data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="bg-gray-50 flex justify-center h-screen">
          <Dashboard />
        </div>
      </main>
    </div>
  );
};

export default Home;
